### ISSUE TITLE
can i install it through pip?

### ISSUE THREAD

**Issue by adaaaaaa** [Vectordash/vectordash-host#2]
while i got this information...and my system is Manjaro x64
[pip.txt](https://github.com/Vectordash/vectordash-host/files/1846228/pip.txt)

**Comment by erbzz** [comment]
I am unfamiliar with Manjaro x64 but you should be able to pip install it on any form of linux, so long as you have python and pip installed. 

Just run `pip install vdhost -U` for the most recent version.
